//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcjQueryTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class jobdetail
    {
        public int JobID { get; set; }

        [DisplayName("Task Name")]
        public string Task_Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Date Started")]
        public string Date_Started { get; set; }

        [DisplayName("Date Finished")]
        public string Date_Finished { get; set; }
        public string Status { get; set; }
    }
}
